Feature/models
Jordancsb/beacademy-devstart-diamante pull request #20
Opened 2022-07-04 17:59 UTC by Jphn

2022-07-04 19:17 UTC, nicolay-padalko commented
Tudo certo.

2022-07-04 22:35 UTC, marcosx3 requested changes

2022-07-04 22:35 UTC, marcosx3 commented on app/Models/Product.php
> +    protected $fillable = [
Faltou coluna para o link da imagem.

2022-07-04 22:58 UTC, Jphn commented on app/Models/Product.php
> +    protected $fillable = [
Vi agora @marcosx3 , vou corrigir após a reunião. Obrigado pela observação!

2022-07-04 23:18 UTC, marcosx3 approved these changes

2022-07-04 23:34 UTC, nvdanilo approved these changes

2022-07-05 11:11 UTC, nicolay-padalko approved these changes

2022-07-05 13:04 UTC, merged