Pagina de cadastro de Produto, criado controller de Produto e rotas
Jordancsb/beacademy-devstart-diamante pull request #22
Opened 2022-07-05 19:47 UTC by marcosx3

2022-07-05 19:50 UTC, Jphn commented on app/Http/Controllers/ProdutoController.php
> +        dd($produto);
Deixou um dd aqui. Ainda está debugando as funcionalidades?

2022-07-05 19:53 UTC, Jphn commented on resources/views/pages/cadastro.blade.php
> +               <input type="text" class="form-control" id="name">
Seria interessante a adição da propriedade `required` nos inputs.

2022-07-05 19:54 UTC, marcosx3 commented on app/Http/Controllers/ProdutoController.php
> +        dd($produto);
Estava sim, testando para ver se o form estava enviando informações.

2022-07-05 20:03 UTC, nicolay-padalko approved these changes

2022-07-05 22:03 UTC, Jphn commented on resources/views/pages/cadastro.blade.php
> +               <input type="text" class="form-control" id="name" required>
Notei agora, mas é necessário que os inputs tenham o atributo `name=""` para que apareçam sejam enviados e nomeados via o método POST. 
```html
<input type="text" class="form-control" id="name" name="name" required>
```
Sei que fica estranho esse exemplo, mas coincide que é o input do nome de usuário.

2022-07-05 22:06 UTC, Jphn requested changes
Adicionar o atributo `name` nos inputs.

2022-07-05 23:29 UTC, nvdanilo approved these changes

2022-07-06 13:01 UTC, Jordancsb approved these changes

2022-07-06 13:01 UTC, merged