Tela para simples listagem de produtos
Jordancsb/beacademy-devstart-diamante pull request #25
Opened 2022-07-06 18:45 UTC by marcosx3

2022-07-06 20:45 UTC, Jphn requested changes
Arquivos: `ProductController.php` e `web.php`
Mudanças comentadas nos devidos arquivos.

2022-07-06 20:45 UTC, Jphn commented on routes/web.php
> +Route::get('/produtos/store',[ProductController::class, 'listProduct'])->name('product.list');
Pode padronizar aqui? Assim como fiz lá em cima.
A rota `/produtos` é referente a tabela produtos do banco de dados e não apresentará nenhuma interface de comunicação direta com o usuário.

Ficaria assim:
```php
Route::get('/produto/store',[ProductController::class, 'listProduct'])->name('product.list');
```

2022-07-06 20:45 UTC, Jphn commented on app/Http/Controllers/ProductController.php
> +    public function listProduct() {
Pode colocar o método http no início da função?
Ex.: `getListProducts`.
Da mesma forma com o método abaixo deste.

Padroniza o desenvolvimento e facilita em futuras refatorações de código.

2022-07-06 20:45 UTC, Jphn commented on app/Http/Controllers/ProductController.php
> +        $products = DB::select('select * from products');
Aqui fica mais simples utilizando o model da tabela participantes.
Ficaria assim:
```php
$products = Product::all();
```

Acredito que desta outra maneira também funciona, mas essa primeira é garantida que sim.
```php
$products = $this->model::all();
```

2022-07-06 20:45 UTC, Jphn commented on routes/web.php
> +Route::post('produtos/store',[ProductController::class,'product.card'])->name('product.card');
Esta rota vai ser responsável por qual funcionalidade?

2022-07-06 22:10 UTC, marcosx3 commented on routes/web.php
> +Route::get('/produtos/store',[ProductController::class, 'listProduct'])->name('product.list');
o problema que essa seria a lista, nosso store, acho que faz mais sentido colocar no plural.

2022-07-06 22:12 UTC, marcosx3 commented on app/Http/Controllers/ProductController.php
> +        $products = DB::select('select * from products');
alterado.

2022-07-06 22:14 UTC, marcosx3 commented on routes/web.php
> +Route::post('produtos/store',[ProductController::class,'product.card'])->name('product.card');
- A primeira para exibição dos produtos onde a pessoa vai escolher se coloca no carrinho de compras.
 - A segunda seria o proprio carrinho, pode-se armazenar uma lista dos produtos escolhidos pelo consumidor.

2022-07-06 22:20 UTC, marcosx3 commented on app/Http/Controllers/ProductController.php
> +    public function listProduct() {
Alterado.

2022-07-06 22:33 UTC, Jphn commented
Subiu o commit das alterações já @marcosx3 ?

2022-07-06 22:59 UTC, marcosx3 commented
> Subiu o commit das alterações já @marcosx3 ?

@Jphn  subi agora.

2022-07-06 23:40 UTC, nicolay-padalko approved these changes

2022-07-07 11:52 UTC, Jphn approved these changes
Tranquilo!
Terminei o meu PR do login de usuário, acho que alguns dos nossos arquivos vão conflitar, mas nada que não possamos resolver no PR.

2022-07-07 12:59 UTC, closed without merging