carrinho formulario de pagamento
Jordancsb/beacademy-devstart-diamante pull request #29
Opened 2022-07-08 15:12 UTC by neresfabio

Crie uma pagina para o carrinho de teste.

2022-07-08 16:06 UTC, marcosx3 commented on app/Http/Controllers/CarrinhoController.php
> +        return view('carrinho.index');
Alterar o nome da view para inglês.

2022-07-08 17:14 UTC, Jphn requested changes
Mudanças para padronização do código.

2022-07-08 17:14 UTC, Jphn commented on routes/web.php
> +Route::get('/carrinho',[CarrinhoController::class,'index'])->name('carrinho.index');
Padronizar o nome da rota para o inglês.
`name('carrinho.index');`

2022-07-08 17:14 UTC, Jphn commented on resources/views/carrinho/index.blade.php
> +<!DOCTYPE html>
Padronizar a nomenclatura da pasta para o inglês.
`/carrinho/`

2022-07-08 20:32 UTC, neresfabio commented on app/Http/Controllers/CarrinhoController.php
> +        return view('carrinho.index');
feito.

2022-07-08 20:32 UTC, neresfabio commented on routes/web.php
> +Route::get('/carrinho',[CarrinhoController::class,'index'])->name('carrinho.index');
feito.

2022-07-09 14:52 UTC, nicolay-padalko submitted a review, later dismissed

2022-07-09 19:34 UTC, Jphn requested changes
Padronizações de código.

2022-07-09 19:34 UTC, Jphn commented on routes/web.php
> +Route::get('/cart',[CarrinhoController::class,'index'])->name('cart.index');
Nome da classe está em português.

2022-07-09 19:34 UTC, Jphn commented on resources/views/partial/navbar.blade.php
> +					<a class="nav-link " href="/cart">Pedidos</a>
Usar o blade.
`{{ route('cart.index') }}`

2022-07-09 19:34 UTC, Jphn commented on app/Http/Controllers/CarrinhoController.php
> +class CarrinhoController extends Controller
Nome do arquivo e da classe estão em português.

2022-07-11 20:05 UTC, closed without merging