feature/products-edit-delete
Jordancsb/beacademy-devstart-diamante pull request #31
Opened 2022-07-13 00:02 UTC by nvdanilo

Adição da página de listagem dos produtos para o administrador, com botões para editar e deletar.

2022-07-13 00:22 UTC, marcosx3 approved these changes
Na page Details poderia ser usado {{ }} ao invés de echo, mas ficou sensacional!

2022-07-13 02:12 UTC, nicolay-padalko approved these changes

2022-07-13 20:43 UTC, rafaelarbz approved these changes

2022-07-13 20:43 UTC, rafaelarbz approved these changes

2022-07-13 23:15 UTC, nvdanilo commented
> Na page Details poderia ser usado {{ }} ao invés de echo, mas ficou sensacional!

A Details eu só copiei já pronta da Show, que alguém já havia feito, hehe. Nas outras utilizei o {{ }}

2022-07-14 13:07 UTC, nicolay-padalko approved these changes

2022-07-14 15:50 UTC, Jphn requested changes
Comentadas.

2022-07-14 15:50 UTC, Jphn commented on resources/views/product/details.blade.php
> +                <img src="<?php echo $product->image_url; ?>" class="card-img-top" alt="...">
Poderia utilizar o `{{  }}` do blade aqui.

2022-07-14 15:50 UTC, Jphn commented on resources/views/product/details.blade.php
> +                    <h5 class="card-title"><?php echo $product->name; ?></h5>
Mesmo para este e os demais abaixo.
```php
<h5 class="card-title">{{ $product->name }}</h5>
```

2022-07-14 15:50 UTC, Jphn commented on routes/web.php
> +Route::post('/produtos/store', [ProductController::class,'product.card'])->name('product.card');
Atenção com a nomenclatura do método `product.card`, se apresentada no código retornará erro de sintaxe.

2022-07-14 22:18 UTC, nvdanilo commented on resources/views/product/details.blade.php
> +                <img src="<?php echo $product->image_url; ?>" class="card-img-top" alt="...">
Sim, essa parte eu só copiei de outra view que alguém já havia feito. Mas vou alterar aqui. Obrigado pelo toque, João.

2022-07-14 22:19 UTC, nvdanilo commented on routes/web.php
> +Route::post('/produtos/store', [ProductController::class,'product.card'])->name('product.card');
Essa parte não foi eu que criei, mas vou conferir aqui. (:

2022-07-14 22:54 UTC, Jphn commented on routes/web.php
> +Route::post('/produtos/store', [ProductController::class,'product.card'])->name('product.card');
Tranquilo Danilo!

2022-07-14 22:57 UTC, Jphn approved these changes

2022-07-14 23:00 UTC, marcosx3 approved these changes

2022-07-15 14:30 UTC, merged