Feature Carrinho de Compras
Jordancsb/beacademy-devstart-diamante pull request #42
Opened 2022-07-23 18:28 UTC by rafaelarbz

- Adicionar ao carrinho(verifica se o produto já está adicionado, se estiver itera a quantidade existente no carrinho, caso não esteja, adiciona ao carrinho normalmente com o status 'RE' (reservado) e  a quantidade de item padrão igual a 1);
- Remover item do carrinho;
- Aumentar/Diminuir a quantidade do item no carrinho (ao modificar a quantidade do produto, a ação grava a nova quantidade no banco e atualiza a soma de todos os itens do carrinho levando em consideração a quantidade de itens. Caso a quantidade seja diminuída até 0 então o item é removido do carrinho e a soma de todos os itens é atualizada) ;
- Atualização de Views e Routes para acionar as novas funcionalidades;
- Na view de  Produtos fiz uma correção pois o valor mostrado no card estava o preço de custo e não o valor de venda;

2022-07-24 09:42 UTC, marcosx3 requested changes

2022-07-24 09:42 UTC, marcosx3 commented on .env.example
> -APP_ENV=local
Esse arquivo tem que subir pro github, pois é com ele que temos acesso ao mesmo nome do BD e demais configurações.

2022-07-25 12:25 UTC, Jphn requested changes
.env.example e outros comentários.

2022-07-25 12:25 UTC, Jphn commented on app/Http/Controllers/CartController.php
> +        $purchases = DB::table('orders')
Acredito que seja melhor o uso dos relacionamentos do laravel.

2022-07-25 12:25 UTC, Jphn commented on app/Models/Order.php
> +        'client_id',
Nomenclatura deste campo deve ser `user_id`.

2022-07-26 21:09 UTC, merged

2022-07-27 14:16 UTC, rafaelarbz commented on app/Models/Order.php
> +        'client_id',
A tabela 'orders' criada com as migrations do projeto quando clonei pela primera vez , estava com essa campo 'client_id' ao invés de 'user_id'. Se confirmares que posso corrigir começarei a corrigir o código para a nomenclatura adequada.

2022-07-27 14:28 UTC, rafaelarbz commented on app/Http/Controllers/CartController.php
> +        $purchases = DB::table('orders')
Neste primeiro momento não consegui ajustar com relacionamentos, por conta do cálculo levar em consideração a quantidade de produtos que está na tabela ORDERS e precisar acessar o valor de cada produtos que está na tabela PRODUCTS, assim então fazer a multiplicação por produto e depois somar. Então foi o que pareceu mais eficiente e direto no primeiro momento.